# Generated by Django 3.2 on 2022-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1', models.CharField(blank=True, max_length=200, null=True)),
                ('sensor2', models.CharField(blank=True, max_length=200, null=True)),
                ('sensor3', models.CharField(blank=True, max_length=200, null=True)),
                ('sensor4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
